Problem: Need to add timestamp column when creating indexes and constraints
The importer failed at the end of the import when it tries to create
the indexes with this error:
ERROR:  cannot create a unique index without the column "timestamp"
(used in partitioning)

We added the "timestamp" column to the two lines of code where we
create an index on blocks columns.